version: '3.8'

services:
  python:
    image: adnsoa/conversao-distancia:v1
    container_name: conversao-distancia
    build:
      dockerfile: ./Dockerfile
      context: ./
    ports:
      - 5000:5000